name: "setup konan cache"
description: "chache .konan directory"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
      id: cache-sdkman
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('tink/build.gradle.kts') }}
        restore-keys: |
          v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}
          v1-konan-${{ runner.os }}
