name: "setup konan cache"
description: "chache .konan directory"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      id: cache-sdkman
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('tink/build.gradle.kts') }}
        restore-keys: |
          v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}
          v1-konan-${{ runner.os }}
