name: "setup konan cache"
description: "chache .konan directory"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      id: cache-sdkman
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('tink/build.gradle.kts') }}
        restore-keys: |
          v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}
          v1-konan-${{ runner.os }}
