name: "setup konan cache"
description: "chache .konan directory"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      id: cache-sdkman
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('tink/build.gradle.kts') }}
        restore-keys: |
          v1-konan-${{ runner.os }}-${{ hashFiles('build.gradle.kts') }}
          v1-konan-${{ runner.os }}
