name: "setup sdkman"
description: "install sdkman"
runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v3
      id: cache-sdkman
      with:
        path: |
          ~/.sdkman
        key: v1-sdkman-${{ runner.os }}-${{ hashFiles('.sdkmanrc') }}

    - if: ${{ steps.cache-sdkman.outputs.cache-hit != 'true' }}
      name: install sdkman
      shell: bash
      run: |
        export SDKMAN_DIR="$HOME/.sdkman" && curl -s "https://get.sdkman.io" | bash

    - name: setup sdkman
      shell: bash
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk env install        
        which sdk >> $GITHUB_PATH
        echo $HOME/.sdkman/candidates/java/current >> $GITHUB_PATH

    - if: ${{ steps.cache-sdkman.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.sdkman
        key: v1-sdkman-${{ runner.os }}-${{ hashFiles('.sdkmanrc') }}
