name: "select xcode"
description: "setup sdkman and install via .xcode-version"
runs:
  using: "composite"
  steps:
    - if: ${{ steps.cache-sdkman.outputs.cache-hit != 'true' }}
      name: read .xcode-version
      shell: bash
      run: |
        echo "XCODE_VERSION=$(cat .xcode-version)" >> $GITHUB_ENV

    - name: execute xcode-select
      shell: bash
      run: |
        xcode-select --switch "/Applications/Xcode_$XCODE_VERSION.app"
