name: lint
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  lint-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      - uses: sdkman/sdkman-action@main
      - run: |
          export JAVA_HOME=$HOME/.sdkman/candidates/java/current
          export PATH=$JAVA_HOME/bin:$PATH
          echo $JAVA_HOME
          echo $PATH
          source "$HOME/.sdkman/bin/sdkman-init.sh"
      - run: sdk env && ./gradlew lint detekt
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: "**/build/reports/lint-results*.xml"
      - run: < ./build/reports/detekt/detekt.xml reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      - uses: sdkman/sdkman-action@main
      - run: |
          export JAVA_HOME=$HOME/.sdkman/candidates/java/current
          export PATH=$JAVA_HOME/bin:$PATH
