name: lint
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
      - uses: reviewdog/action-yamllint@v1
      - uses: reviewdog/action-markdownlint@v0

  lint-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      # TODO replace after release
      # - uses: sdkman/sdkman-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: lint detekt
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: "**/build/reports/lint-results*.xml"
          continue-on-error: false
      - run: cat ./build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      # TODO replace after release
      # - uses: sdkman/sdkman-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
