name: release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@v2
      - run: make bootstrap-submodule
      - uses: actions/cache@v3
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - run: make archive
      - uses: nick-fields/retry@v2.8.3
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 40
          command: ./gradlew publishAllPublicationsToSonatypeRepository --stacktrace
