name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: main
          release-type: simple
          package-name: release-please-action
          include-v-in-tag: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
