name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: macos-13
    steps:
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3
        id: release
        with:
          default-branch: main
          release-type: simple
          package-name: release-please-action
          include-v-in-tag: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/sdkman
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/konan
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/xcode-select
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.153.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2
        if: ${{ steps.release.outputs.release_created }}
      - run: make bootstrap-submodule
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - run: make archive
        if: ${{ steps.release.outputs.release_created }}
      - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # v2.8.3
        if: ${{ steps.release.outputs.release_created }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 40
          command: ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository --stacktrace
