name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: macos-14
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
        id: release
        with:
          default-branch: main
          release-type: simple
          package-name: release-please-action
          include-v-in-tag: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/sdkman
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/konan
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/xcode-select
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@401c19e14f474b54450cd3905bb8b86e2c8509cf # v1.204.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3
        if: ${{ steps.release.outputs.release_created }}
      - run: make bootstrap-submodule
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - run: make archive
        if: ${{ steps.release.outputs.release_created }}
      - uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        if: ${{ steps.release.outputs.release_created }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
          PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 40
          command: ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository --stacktrace
