name: test-ios
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # TODO replace after release
      # - uses: sdkman/sdkman-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@v2
      - run: make bootstrap-submodule
      - uses: actions/cache@v3
        with:
          path: |
            TinkStub/objc/bazel-bin
            TinkStub/objc/bazel-objc
            TinkStub/objc/bazel-out
            Framework/Tink.xcframework
          key: v1-bazel-${{ runner.os }}-${{ hashFiles('Framework/Podfile') }}
      - run: make archive
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: iosX64Test
      - uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: Test Results iOSX64
          files: |
            **/test-results/**/*.xml
