name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3
        with:
          gradle-home-cache-cleanup: true
          arguments: testDebugUnitTest --scan
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3
        with:
          gradle-home-cache-cleanup: true
          arguments: jacocoMergedReport
      - uses: EnricoMi/publish-unit-test-result-action@e22cb89252eed6924b77cf94ec9d7776e0d2bc0d # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Test Results android
          files: |
            **/test-results/**/*.xml
      - uses: codecov/codecov-action@0cfda1dd0a4ad9efc75517f399d859cd1ea4ced1 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  unit-test-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/xcode-select
      - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3
      - run: make bootstrap-submodule
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
        id: framework
        with:
          files: "Framework/Tink.xcframework"
      - run: make archive
        if: steps.framework.outputs.files_exists != 'true'
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3
        with:
          gradle-home-cache-cleanup: true
          arguments: iosX64Test --scan
      - uses: EnricoMi/publish-unit-test-result-action/composite@e22cb89252eed6924b77cf94ec9d7776e0d2bc0d # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Unit Test Results iosX64
          files: |
            **/test-results/**/*.xml

  instrumented-test-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/xcode-select
      - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3
      - run: make bootstrap-submodule
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
        id: framework
        with:
          files: "Framework/Tink.xcframework"
      - run: make archive
        if: steps.framework.outputs.files_exists != 'true'
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3
        with:
          gradle-home-cache-cleanup: true
          arguments: :iosApp:simulatorsList
      - uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3
        with:
          gradle-home-cache-cleanup: true
          arguments: :iosApp:xcodetest --scan --info
      - uses: EnricoMi/publish-unit-test-result-action/composite@e22cb89252eed6924b77cf94ec9d7776e0d2bc0d # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Instrumented Test Results iosX64
          files: |
            **/test-results.xml
