name: test-android
on: pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO replace after release
      # - uses: sdkman/sdkman-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - run: java -version
      - run: ./gradlew tasks
