name: test-android
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sdkman/sdkman-action@main
      - run: |
          export JAVA_HOME=$HOME/.sdkman/candidates/java/current
          export PATH=$JAVA_HOME/bin:$PATH
          echo $JAVA_HOME
          echo $PATH
          source "$HOME/.sdkman/bin/sdkman-init.sh"
      - run: sdk env && ./gradlew testDebugUnitTest jacocoMergedReport
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results android
          files: |
            **/test-results/**/*.xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
