name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: testDebugUnitTest --scan
      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: jacocoMergedReport
      - uses: EnricoMi/publish-unit-test-result-action@ca89ad036b5fcd524c1017287fb01b5139908408 # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Test Results android
          files: |
            **/test-results/**/*.xml
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  unit-test-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/xcode-select
      - uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2
      - run: make bootstrap-submodule
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2
        id: framework
        with:
          files: "Framework/Tink.xcframework"
      - run: make archive
        if: steps.framework.outputs.files_exists != 'true'
      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: iosX64Test --scan
      - uses: EnricoMi/publish-unit-test-result-action/composite@ca89ad036b5fcd524c1017287fb01b5139908408 # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Unit Test Results iosX64
          files: |
            **/test-results/**/*.xml

  instrumented-test-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/sdkman
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/xcode-select
      - uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
        with:
          bundler-cache: true
      - uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2
      - run: make bootstrap-submodule
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: |
            build/bazel
            Framework/Tink.xcframework
          key: v2-bazel-${{ runner.os }}-${{ hashFiles('.git/modules/TinkStub/HEAD') }}
      - uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2
        id: framework
        with:
          files: "Framework/Tink.xcframework"
      - run: make archive
        if: steps.framework.outputs.files_exists != 'true'
      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: :iosApp:simulatorsList
      - uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: :iosApp:xcodetest --scan --info
      - uses: EnricoMi/publish-unit-test-result-action/composite@ca89ad036b5fcd524c1017287fb01b5139908408 # v2
        if: ${{ !cancelled() && (success() || failure()) }}
        with:
          check_name: Instrumented Test Results iosX64
          files: |
            **/test-results.xml
